all: Angle BlinkAnimation Blink Image PrintCharAnimationRus PrintTickerRus

Angle: ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp
BlinkAnimation: ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp
Blink: ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp
Image: ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp
PrintCharAnimationRus: ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp
PrintTickerRus : ../iarduino_I2C_Matrix_8x8.cpp ../WString.cpp ../itoa.cpp ../dtostrf.cpp ../iarduino_I2C_PI.cpp

clean:
	rm -f Angle BlinkAnimation Blink Image PrintCharAnimationRus PrintTickerRus
